version: 2.1
jobs:
  end-to-end:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      # - restore_cache:
      #     # See the configuration reference documentation for more details on using restore_cache and save_cache steps
      #     # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
      #     keys:
      #       - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      # - run:
      #     name: install packages
      #     command: npm ci
      # - save_cache:
      #     key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      #     paths:
      #       - ~/.npm
      - run:
          name: Run End-to-End tests
          command: yarn add cypress
          command: yarn e2e:cmd

  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      # - restore_cache:
      #     # See the configuration reference documentation for more details on using restore_cache and save_cache steps
      #     # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
      #     keys:
      #       - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      # - run:
      #     name: install packages
      #     command: npm ci
      # - save_cache:
      #     key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      #     paths:
      #       - ~/.npm
      - run:
          name: Run Tests
          command: yarn test

workflows:
  orb-free-workflow:
    jobs:
      - end-to-end
      - test
